### ISSUE TITLE
backprop into text_condition

### ISSUE THREAD

**Issue by WERush** [LuoweiZhou/e2e-gLSTM-sc#1]
Hi, i am confused about your code when you backprop into the text_condition, the line is https://github.com/LuoweiZhou/e2e-gLSTM-sc/blob/master/misc_tc/LanguageModel_sc.lua#L469, why you use the `text_condition` as the input of backward, by my understanding, i think the input should be `it_s`, i mean this line should be `self.lookup_tables_tc[t]:backward(it_s, dimg_text[2])`, because the forward of text_condition is `self.lookup_tables_tc[t]:forward(it_s)`, that's similar to the forward and backward of `self.lookup_tables[t]`, can you explain it for me? thanks

**Comment by LuoweiZhou** [comment]
Hello Xinge,

Thanks for your interest in the code. Yes, you are right, it should be
it_s. This affects the derivative of the weights and will affect the final
results.
I am fixing this bug and will re-run the code. I will inform you when the
results are ready. Thanks for your effort to improve the code.

best,
Luowei

--------------------------
Luowei Zhou
(luoweizhou.net/about.html)
Robotics Institute
University of Michigan-Ann Arbor
48105, Ann Arbor, MI

**Comment by WERush** [comment]
Thanks for your reply.
 i have another question about your model, by my understanding, the file `train_new.lua` and `misc_new/LanguageModel.lua` is used to build a model without text_condition, isn't it?

Maybe the figure4 in your paper is a little misunderstanding, because the text_condition is obtained after `W_e * [one-hot]`, but in fact the text_condition is obtained by `W_c * [one-hot]`, not used the `W_e *[one-hot]`, do i understand it correctly? hope you can help me. thanks

**Comment by LuoweiZhou** [comment]
Hello Xinge,

Yes, the train_new.lua is used for e2e-gLSTM, no text_condition needed.
Yes, you are right. Sorry about the mistake. I will fix all those issues
and keep you informed.

Thanks. Keep in touch!

best,
Luowei

--------------------------
Luowei Zhou
(luoweizhou.net/about.html)
Robotics Institute
University of Michigan-Ann Arbor
48105, Ann Arbor, MI

**Comment by WERush** [comment]
Thanks for your reply, Luowei.

Hope your paper can be accepted, good luck.

Xinge.
