### ISSUE TITLE
code release for "End-to-End Dense Video Captioning with Masked Transformer"

### ISSUE THREAD

**Issue by sophia-wright-blue** [LuoweiZhou/e2e-gLSTM-sc#8]
Hello,

 Is there a near-term plan to release the code for your paper - "End-to-End Dense Video Captioning with Masked Transformer"?

Thanks,

**Comment by LuoweiZhou** [comment]
Hi @sophia-wright-blue, we plan to release the code soon. Please stay tuned! And you can reach me at my email luozhou@umich.edu for more details in the future
