### ISSUE TITLE
e2e-gLSTM-sc为什么要从e2eglstm-checkpoint 开始训练？

### ISSUE THREAD

**Issue by mymuli** [LuoweiZhou/e2e-gLSTM-sc#9]
命令：-start_from /path/to/your/e2eglstm-checkpoint

**Comment by LuoweiZhou** [comment]
Hi @Rmuli, it's mentioned in Sec. 4.1, par 2 of the [paper](https://dl.acm.org/citation.cfm?id=3126717)
